spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: "jdbc:mysql://localhost:3307/alarmsystem?useSSL=false"
    username: "root"
    password: "secret"
server:
  port: 8090
#liquibase:
#  change-log: "classpath:db/db.changelog-master.yaml"